import { validateDraft } from "@whatsapp-bot-platform/compiler";
import { generateWithConfidence } from "@whatsapp-bot-platform/eval";
import type { GenerateAttempt } from "@whatsapp-bot-platform/eval";
import type { DraftConfig, PrimitiveFieldValues, PrimitiveKey, ValidationResult } from "@whatsapp-bot-platform/shared-types";

export type GenerateFieldValuesFn = (context: {
  lobKey: string | null;
  primitiveKey: PrimitiveKey;
  attempt: number;
  previousAttempts: readonly GenerateAttempt<PrimitiveFieldValues>[];
}) => Promise<PrimitiveFieldValues>;

export interface GenerateGroundTruthOptions {
  /**
   * The exact primitive set to generate for — matches how the real interview
   * has selected primitives since capability-driven classification replaced
   * the old LOB-recipe lookup (packages/schema's lob_recipes.ts is now
   * informational-only, not a source of truth for what a draft contains).
   */
  selectedPrimitives: readonly PrimitiveKey[];
  /** Purely descriptive metadata carried onto the generated DraftConfig — never used to look up primitives. */
  lobKey?: string | null;
  generateFieldValues: GenerateFieldValuesFn;
  maxAttemptsPerPrimitive?: number;
}

function summarizeValidationFailure(validation: ValidationResult): string {
  const errorCount = validation.issues.filter((issue) => issue.severity === "error").length;
  return `${validation.missingRequiredFields.length} missing field(s), ${errorCount} error(s)`;
}

/**
 * Narrows a validateDraft() result down to only what's attributable to one
 * primitive. Needed because the per-primitive probe below includes every
 * selected primitive (so presence-based cross-primitive checks like
 * "faq_support requires human_escalation" see the full picture), but only
 * populates the *current* primitive's fieldValues — every sibling primitive
 * not yet generated by its own concurrent attempt would otherwise show up as
 * "missing all required fields," which is an artifact of the probe, not a
 * real problem with the primitive actually being scored.
 */
function attributedTo(validation: ValidationResult, primitiveKey: PrimitiveKey): ValidationResult {
  const missingRequiredFields = validation.missingRequiredFields.filter((f) => f.primitiveKey === primitiveKey);
  const issues = validation.issues.filter((i) => i.primitiveKey === primitiveKey && i.severity === "error");
  return { valid: missingRequiredFields.length === 0 && issues.length === 0, missingRequiredFields, issues };
}

/**
 * Generates a ground-truth DraftConfig for an explicit primitive set — one
 * that is guaranteed to actually pass packages/compiler's validateDraft, not
 * just assumed to. Each primitive's fields are generated through the same
 * shared generateWithConfidence() every other LLM call site in the system
 * uses (see packages/eval): "confidence" here is just pass/fail from
 * validateDraft, with the validation summary threaded back as feedback for
 * the next retry. Primitives don't depend on each other, so they generate
 * concurrently; a final validation pass on the assembled draft catches
 * cross-primitive constraints (e.g. booking needs business_info.hours) no
 * single primitive's fields can surface on their own.
 */
export async function generateGroundTruthDraft(options: GenerateGroundTruthOptions): Promise<DraftConfig> {
  const { selectedPrimitives, lobKey = null, generateFieldValues, maxAttemptsPerPrimitive = 3 } = options;

  const generated = await Promise.all(
    selectedPrimitives.map(async (primitiveKey): Promise<[PrimitiveKey, PrimitiveFieldValues]> => {
      const result = await generateWithConfidence<PrimitiveFieldValues>({
        generate: async ({ attempt, previousAttempts }) => ({
          output: await generateFieldValues({ lobKey, primitiveKey, attempt, previousAttempts }),
          confidence: 0, // authoritative confidence comes from score() below, not self-reported
        }),
        score: async (values) => {
          const probe: DraftConfig = {
            draftSessionId: "synthetic-probe",
            version: 1,
            lobKey,
            // the full selected set, not just [primitiveKey]: presence-based cross-primitive
            // checks (e.g. faq_support requires human_escalation) need to see every
            // primitive that will ultimately be selected, not an artificially narrowed set
            selectedPrimitives,
            fieldValues: { [primitiveKey]: values },
          };
          const validation = attributedTo(validateDraft(probe), primitiveKey);
          return {
            confidence: validation.valid ? 1 : 0,
            reason: validation.valid ? undefined : summarizeValidationFailure(validation),
          };
        },
        threshold: 1,
        maxAttempts: maxAttemptsPerPrimitive,
      });

      if (result.status === "low_confidence") {
        throw new Error(
          `Failed to generate valid field values for primitive "${primitiveKey}" ` +
            `after ${maxAttemptsPerPrimitive} attempts: ${result.lastReason ?? "validation failed"}.`,
        );
      }

      return [primitiveKey, result.output];
    }),
  );

  const draft: DraftConfig = {
    draftSessionId: `synthetic-${lobKey ?? "custom"}-${Date.now()}`,
    version: 1,
    lobKey,
    selectedPrimitives,
    fieldValues: Object.fromEntries(generated),
  };

  const finalValidation = validateDraft(draft);
  if (!finalValidation.valid) {
    throw new Error(
      `Generated ground-truth draft for primitives [${selectedPrimitives.join(", ")}] failed full validation ` +
        `(cross-primitive constraint likely): ${summarizeValidationFailure(finalValidation)}.`,
    );
  }

  return draft;
}
